### ISSUE TITLE
bechmark

### ISSUE THREAD

**Issue by wangjiawen2013** [LouisFaure/deseq2py#1]
Hi,
very useful work!
Why do you develop this tool and do you compare it with DEseq2 on some datasets ?

**Comment by LouisFaure** [comment]
Thank you for your interest! I am afraid this package is simply some wrappers of DESeq2 R package, as most functions actually call R through rpy2. This means one should not expect changes in term of speed or results (except maybe for the PCA, which is now performed by scanpy)

The aim of this project is to combine the quality of analysis of DESeq2 with the flexibility of data manipulation and plotting of anndata/scanpy.

The idea is also to use this in combination with https://github.com/LouisFaure/bulktools-py, a cli wrapper that generates count matrix in anndata format from raw bulk rnaseq fastq files :)

**Comment by wangjiawen2013** [comment]
Good idea, and this is what I want to do for a long time ! Thank you !

**Comment by wangjiawen2013** [comment]
Hi,
please helps !
(spatial) [wangjw@localhost spatial]$ python
Python 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:59:51) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import deseq2py as deseq
Traceback (most recent call last):
  File "/home/wangjw/programs/miniconda3/envs/spatial/lib/python3.8/site-packages/rpy2/rinterface_lib/openrlib.py", line 17, in <module>
    import _rinterface_cffi_api as _rinterface_cffi  # type: ignore
ImportError: libffi.so.7: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wangjw/programs/deseq2py/deseq2py/tools/deseq2.py", line 10, in <module>
    from rpy2.robjects import pandas2ri, Formula
  File "/home/wangjw/programs/miniconda3/envs/spatial/lib/python3.8/site-packages/rpy2/robjects/__init__.py", line 15, in <module>
    import rpy2.rinterface as rinterface
  File "/home/wangjw/programs/miniconda3/envs/spatial/lib/python3.8/site-packages/rpy2/rinterface.py", line 14, in <module>
    from rpy2.rinterface_lib import openrlib
  File "/home/wangjw/programs/miniconda3/envs/spatial/lib/python3.8/site-packages/rpy2/rinterface_lib/openrlib.py", line 19, in <module>
    import _rinterface_cffi_abi as _rinterface_cffi  # type: ignore
  File "/home/wangjw/programs/miniconda3/envs/spatial/lib/python3.8/site-packages/_rinterface_cffi_abi.py", line 2, in <module>
    import _cffi_backend
ImportError: libffi.so.7: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wangjw/programs/deseq2py/deseq2py/__init__.py", line 2, in <module>
    from . import tl
  File "/home/wangjw/programs/deseq2py/deseq2py/tl.py", line 1, in <module>
    from deseq2py.tools import *
  File "/home/wangjw/programs/deseq2py/deseq2py/tools/__init__.py", line 1, in <module>
    from .deseq2 import run, vst, pca, show_results, result, save, read
  File "/home/wangjw/programs/deseq2py/deseq2py/tools/deseq2.py", line 18, in <module>
    + task
NameError: name 'task' is not defined
>>>

**Comment by LouisFaure** [comment]
I am not sure that this is directly related to my code. It seems to be an error linked to rpy2 and your current environment. Maybe this is related to the OS you are using? 
I have successfully tested it on Ubuntu 20.04 as well as WSL
